config/routes.rb
Drugstore::Application.routes.draw do

  resources :inventories

  resources :purchases do
    resources :purchase_items
  end

  resources :sales do
    resources :sale_items
  end

  get '/' => 'home#index', :as => 'home'

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Sale
    end
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :medicine_id, :quantity, :sale_price

  belongs_to :medicine
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :medicines
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  attr_accessible :commercial_name, :concentration, :generic_name, :laboratory_id, :presentation_id
  belongs_to :laboratory
  belongs_to :presentation
  has_many :sale_items
  has_many :purchase_items
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :name
  has_many :medicines
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :name

  has_many :purchase_items
end

app/models/purchase_item.rb
class PurchaseItem < ActiveRecord::Base
  attr_accessible :medicine_id, :purchase_id, :container, :quantity, :quantity_unit_container, :price, :due_date

  belongs_to :purchase
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :description

  has_many :sale_items
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  attr_accessible :medicine_id, :sale_id, :quantity, :price

  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #layout 'internal'

  before_filter :authenticate_user!

  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.all
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(params[:purchase])
    if @purchase.save
      redirect_to @purchase, :notice => "Successfully created purchase."
    else
      render :action => 'new'
    end
  end

  def edit
    @purchase = Purchase.find(params[:id])
  end

  def update
    @purchase = Purchase.find(params[:id])
    if @purchase.update_attributes(params[:purchase])
      redirect_to @purchase, :notice  => "Successfully updated purchase."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy
    redirect_to purchases_url, :notice => "Successfully destroyed purchase."
  end
end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
  def index
    @sale_items = SaleItem.all
  end

  def show
    @sale_item = SaleItem.find(params[:id])
  end

  def new
    @sale_item = SaleItem.new
  end

  def create
    @sale_item = SaleItem.new(params[:sale_item])
    if @sale_item.save
      redirect_to @sale_item, :notice => "Successfully created sale item."
    else
      render :action => 'new'
    end
  end

  def edit
    @sale_item = SaleItem.find(params[:id])
  end

  def update
    @sale_item = SaleItem.find(params[:id])
    if @sale_item.update_attributes(params[:sale_item])
      redirect_to @sale_item, :notice  => "Successfully updated sale item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @sale_item = SaleItem.find(params[:id])
    @sale_item.destroy
    redirect_to sale_items_url, :notice => "Successfully destroyed sale item."
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  #layout 'internal'

  before_filter :authenticate_user!

  def index
    @sales = Sale.all
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(params[:sale])
    if @sale.save
      redirect_to @sale, :notice => "Successfully created sale."
    else
      render :action => 'new'
    end
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update_attributes(params[:sale])
      redirect_to @sale, :notice  => "Successfully updated sale."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to sales_url, :notice => "Successfully destroyed sale."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/purchase_items_helper.rb
module PurchaseItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sale_items/_form.html.haml
= form_for @sale_item do |f|
  = f.error_messages
  %p
    = f.label :medicine_id
    %br
    = f.number_field :medicine_id
  %p
    = f.label :sale_id
    %br
    = f.number_field :sale_id
  %p
    = f.label :quantity
    %br
    = f.number_field :quantity
  %p
    = f.label :price
    %br
    = f.text_field :price
  %p
    = f.submit

app/views/sale_items/edit.html.haml
- title "Edit Sale Item"

= render 'form'

%p
  = link_to "Show", @sale_item
  |
  = link_to "View All", sale_items_path

app/views/sale_items/index.html.haml
- title "Sale Items"

%table
  %tr
    %th Medicine
    %th Sale
    %th Quantity
    %th Price
  - for sale_item in @sale_items
    %tr
      %td= sale_item.medicine_id
      %td= sale_item.sale_id
      %td= sale_item.quantity
      %td= sale_item.price
      %td= link_to 'Show', sale_item
      %td= link_to 'Edit', edit_sale_item_path(sale_item)
      %td= link_to 'Destroy', sale_item, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Sale Item", new_sale_item_path

app/views/sale_items/new.html.haml
- title "New Sale Item"

= render 'form'

%p= link_to "Back to List", sale_items_path

app/views/sale_items/show.html.haml
- title "Sale Item"

%p
  %strong Medicine:
  = @sale_item.medicine_id
%p
  %strong Sale:
  = @sale_item.sale_id
%p
  %strong Quantity:
  = @sale_item.quantity
%p
  %strong Price:
  = @sale_item.price

%p
  = link_to "Edit", edit_sale_item_path(@sale_item)
  |
  = link_to "Destroy", @sale_item, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", sale_items_path

app/views/sales/_form.html.haml
= form_for @sale, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :client, :class => 'control-label'
    .controls
      = f.text_field :client, :class => 'text_field'
  .control-group
    = f.label :nit, :class => 'control-label'
    .controls
      = f.text_field :nit, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), sales_path, :class => 'btn'

app/views/sales/edit.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/sales/index.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize

= link_to t('.new', :default => t("helpers.links.new")), new_sale_path, :class => 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:client)
      %th= model_class.human_attribute_name(:nit)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sales.each do |sale|
      %tr
        %td= link_to sale.id, sale_path(sale)
        %td= sale.client
        %td= sale.nit
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_path(sale), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), sale_path(sale), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/sales/new.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/sales/show.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:client) + ':'
  %br
  = @sale.client
%p
  %strong= model_class.human_attribute_name(:nit) + ':'
  %br
  = @sale.nit

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), sales_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_path(@sale), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), sale_path(@sale), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'