config/routes.rb
Drugstore::Application.routes.draw do

  resources :inventories

  resources :purchases do
    resources :purchase_items
  end

  resources :sales do
    resources :sale_items
  end

  get '/' => 'home#index', :as => 'home'

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Sale
    end
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :medicine_id, :quantity, :sale_price

  belongs_to :medicine
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :medicines
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  attr_accessible :commercial_name, :concentration, :generic_name, :laboratory_id, :presentation_id
  belongs_to :laboratory
  belongs_to :presentation
  has_many :sale_items
  has_many :purchase_items
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :name
  has_many :medicines
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :name

  has_many :purchase_items
end

app/models/purchase_item.rb
class PurchaseItem < ActiveRecord::Base
  attr_accessible :medicine_id, :purchase_id, :container, :quantity, :quantity_unit_container, :price, :due_date

  belongs_to :purchase
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :description

  has_many :sale_items
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  attr_accessible :medicine_id, :sale_id, :quantity, :price

  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #layout 'internal'

  before_filter :authenticate_user!

  def index
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  #layout 'internal'

  before_filter :authenticate_user!

  def index
    @sales = Sale.all
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(params[:sale])
    if @sale.save
      redirect_to @sale, :notice => "Successfully created sale."
    else
      render :action => 'new'
    end
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update_attributes(params[:sale])
      redirect_to @sale, :notice  => "Successfully updated sale."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to sales_url, :notice => "Successfully destroyed sale."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/purchase_items_helper.rb
module PurchaseItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title) || t('.title')
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application", :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)

  %body
    %div{:class => 'navbar navbar-fixed-top navbar-inverse'}
      %div{:class => 'navbar-inner'}
        .container
          = link_to '', :class => 'btn btn-navbar', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse' do
            %span{:class => 'icon-bar'}
            %span{:class => 'icon-bar'}
            %span{:class => 'icon-bar'}
          = link_to 'Drugstore', {}, :class => 'brand'
          %div{:class => 'nav-collapse'}
            - if user_signed_in?
              %ul.nav
                %li= link_to 'Home', home_path
                %li= link_to 'Sales', sales_path
                %li= link_to 'Purchases', purchases_path
                %li= link_to 'Inventories', inventories_path, remote: true
                %li= link_to 'Admin Section', admin_dashboard_path if current_user.admin?
                %li= link_to 'Logout', destroy_user_session_path, method: 'delete'

    .container
      .row
        .span12
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}"

          - if show_title?
            %h1= yield(:title)

          = yield

app/views/layouts/internal.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || t('.title')
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "internal", :media => 'all'
    = javascript_include_tag "internal"
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      = link_to 'Logout', destroy_user_session_path, :method => :delete if user_signed_in?
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield